# Generated by Django 2.2.12 on 2022-11-23 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20221115_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_member', models.CharField(max_length=10)),
                ('nama', models.CharField(max_length=100)),
                ('alamat', models.CharField(max_length=120)),
                ('tahun_gabung', models.IntegerField()),
                ('poin', models.IntegerField()),
            ],
        ),
    ]
